#!/usr/bin/env python3
"""Build normalized Castle settlement derivatives from quarantined candidates.

Source masters (NOT promoted production art):
  apps/web/public/art/alpha/imagine-explorations/buildings/*.png

Outputs:
  apps/web/public/art/alpha/castle/buildings/<stem>[-tier].webp
  apps/web/public/art/alpha/castle/atlas.json      (provenance + anchors)
  apps/web/src/lib/castleSceneAtlas.json           (byte-identical runtime copy)

Governance: these derivatives are candidate-derived and are NOT formally
promoted under ALPHA_VISUAL_CONTRACT_V1 (the AGES provider is
BLOCKED_EXTERNAL). Master SHA-256 is recorded so provenance is auditable and
the decision is reversible. `docs/competitive/audits/castle-north-star-v2-convergence.md`
records the full disposition.

The runtime copy is generated here, never hand-edited; a unit test
(`castleSceneAssets.test.ts`) asserts the two atlas files stay identical.

Requires: Python 3 + Pillow (`pip install pillow`).
Usage: python3 apps/web/scripts/build-castle-derivatives.py
"""
from PIL import Image
import os
import json
import glob
import hashlib

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.dirname(HERE)
SRC = os.path.join(WEB, "public/art/alpha/imagine-explorations/buildings")
OUT_DIR = os.path.join(WEB, "public/art/alpha/castle/buildings")
PUBLIC_ATLAS = os.path.join(WEB, "public/art/alpha/castle/atlas.json")
RUNTIME_ATLAS = os.path.join(WEB, "src/lib/castleSceneAtlas.json")

MAX = 560
PAD = 3
# Rejected: baked opaque near-black background (alpha 255 across the frame);
# cannot be composited. Provenance retained; runtime degrades to bronze.
REJECT = {"bld-barracks-gold.png"}


def sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def build() -> dict:
    os.makedirs(OUT_DIR, exist_ok=True)
    atlas = {"rejected": {}}
    for src in sorted(glob.glob(os.path.join(SRC, "*.png"))):
        name = os.path.basename(src)
        if name in REJECT:
            atlas["rejected"][name] = {
                "reason": "baked opaque background (alpha 255 across frame); cannot composite",
                "masterSha256": sha256(src),
            }
            continue
        im = Image.open(src).convert("RGBA")
        bbox = im.getchannel("A").getbbox()
        if bbox is None:
            continue
        l, t, r, b = bbox
        crop = im.crop(
            (max(0, l - PAD), max(0, t - PAD), min(im.width, r + PAD), min(im.height, b + PAD))
        )
        scale = min(1.0, MAX / max(crop.width, crop.height))
        if scale < 1.0:
            crop = crop.resize(
                (max(1, round(crop.width * scale)), max(1, round(crop.height * scale))),
                Image.LANCZOS,
            )
        out = os.path.join(OUT_DIR, name.replace(".png", ".webp"))
        crop.save(out, "WEBP", quality=86, method=4)
        px = crop.getchannel("A").load()
        w, h = crop.size
        bottom = next(
            (y for y in range(h - 1, -1, -1) if any(px[x, y] > 8 for x in range(0, w, 2))),
            h,
        )
        band = max(3, int(h * 0.05))
        y0 = max(0, bottom - band)
        xs = [x for y in range(y0, bottom + 1) for x in range(w) if px[x, y] > 8]
        cx = (min(xs) + max(xs)) / 2 if xs else w / 2
        atlas.setdefault("assets", {})[name] = {
            "src": f"/art/alpha/castle/buildings/{name.replace('.png', '.webp')}",
            "master": f"/art/alpha/imagine-explorations/buildings/{name}",
            "masterSha256": sha256(src),
            "w": w,
            "h": h,
            "anchor": [round(cx / w, 4), round(bottom / h, 4)],
            "bytes": os.path.getsize(out),
        }
    return {
        "note": (
            "Candidate-derived runtime derivatives of quarantined "
            "imagine-explorations masters. NOT formally promoted under "
            "ALPHA_VISUAL_CONTRACT_V1 (AGES provider BLOCKED_EXTERNAL); used as "
            "the interim default under documented owner campaign authority. "
            "Masters retained via masterSha256; decision reversible. This file "
            "is generated by scripts/build-castle-derivatives.py and mirrored "
            "byte-for-byte into src/lib/castleSceneAtlas.json."
        ),
        "generator": "scripts/build-castle-derivatives.py (PIL alpha-trim, max-560, WebP q86 method4)",
        **atlas,
    }


def main() -> None:
    atlas = build()
    payload = json.dumps(atlas, indent=1)
    with open(PUBLIC_ATLAS, "w") as f:
        f.write(payload)
    with open(RUNTIME_ATLAS, "w") as f:
        f.write(payload)
    print(f"wrote {len(atlas.get('assets', {}))} derivatives, rejected={list(atlas['rejected'])}")
    print(f"atlas -> {PUBLIC_ATLAS}")
    print(f"atlas -> {RUNTIME_ATLAS}")


if __name__ == "__main__":
    main()
